version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-cli: circleci/aws-cli@5.1

workflows:
  build-and-push:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: "${AWS_ACCOUNT_ID}"
          auth:
            - aws-cli/setup:
                role_arn: "arn:aws:iam::123456789012:role/VALID_OIDC_ECR_ROLE"
          repo: "myECRRepository"
          tag: "${CIRCLE_SHA1}"
          region: "${AWS_DEFAULT_REGION}"
          create_repo: true
